spring:
  data:
    mongodb:
      host: 192.168.56.101
      database: articledb
      port: 27017
      username: "bobo"
      password: "123456"
#      uri : mongodb://bobo:123456@192.168.56.101:27017/articledb
